name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
        
      - name: Restore NuGet packages
        run: nuget restore CSharpEduLib.sln
        
      - name: Build
        run: msbuild CSharpEduLib.sln /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackages=true
        
      - name: Test
        shell: powershell
        run: |
          # Find test assemblies in Release build output
          $tests = Get-ChildItem -Recurse -Filter *.Tests.dll | Where-Object { $_.FullName -match "\\bin\\Release\\" -and $_.FullName -notmatch "ref|TestHost|TestAdapter|TestFramework" }
          
          if (-not $tests) {
            Write-Host "No test assemblies found"
            exit 1
          }
          
          foreach ($t in $tests) {
            Write-Host "Running tests: $($t.FullName)"
            vstest.console.exe "$($t.FullName)" /Framework:.NETFramework,Version=v4.8
          }